# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              "https://kjw81511.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl:          "" # the subpath of your site, e.g. "/blog"

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

remote_theme : pool/hyde

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
